ocaml-dune/binary-distribution

- README.md
Quick change in the README to reflect the new way of deploying and generating the executables.
> docs: change README to explain the situation

- .github/workflows/binary.yaml
- dune-locking.patch
This is a temporary fix for running the interview. It will be removed as soon as we can merge it into upstream main :+1:
> feat(patch): use the autolocking patch for interviews

- dune-locking.patch
As https://github.com/ocaml/dune/pull/10852 has been merged, we need to update the patch to only apply the relocking message and not the atomic lock modification anymore :+1:
> chore: update patch

- .github/workflows/binary.yaml
Fix after #27 where I forgot to update the CI :facepalm:
> fix: do not forget to remove patch in CI

- Dockerfile
This PR introduces a Dockerfile to make it possible to serve our server using the OCurrent-deployer infrastructure.
> feat: introduce Dockerfile

- sandworm/lib/web.mlx
Some question marks, some table that's not a table.. minor stuff.
> Fix some wording

- sandworm/lib/web.mlx
This PR adds a warning message to make sure people are aware the page will be broken.
> feat: add warning message for development time

- install
I looked at porting to POSIX `sh` but there's a lot of bashisms, so that would need to wait.
> Apply some shellcheck improvements

- lib/web.mlx
- static/install
This PR consists of changing the shebang line to `#!/bin/sh`, and following shellcheck instructions.
Most changes should be obvious, but I'll point out those that seem intriguing
> Make the install script POSIX compatible

- dune-project
- sandworm.opam
This PR intends to give back the credit to the authors of this software.
> chore: update authors and maintainers

- lib/web.mlx
> Fix FAQ typo

- bin/main.ml
- bin/server.ml
- lib/web.mlx
- static/main.css
This PR intends to fix #87 and install an error handler that displays the error code and the reason on the webpage.
> feat: error handling

- .github/workflows/binary.yaml
Forcing it to build is more complicated than I thought. Trying again!
Heads up @maiste.
> Add back check_build but force it to build

- .github/workflows/binary.yaml
> Add back the check_build stage

- lib/web.mlx
Can be reverted when @leostera is back but we don't want people to book calls and never hear back.
> Remove book a call

- shell.nix
Adds some missing dependencies and formats the shell.nix file.
> Nix updates

- completions/bash.sh
Adds completions for new commands and fixes a bug where a space would be inserted after completing a directory name preventing paths from being iteratively completed by pressing tab.
> Update bash completion script

- .ocamlformat
- dune-project
- sandworm.opam
Signed-off-by: Etienne Marais <dev@maiste.fr>
> chore: bump ocamlformat version

- static/install
Signed-off-by: Etienne Marais <dev@maiste.fr>
> fix: typo in install script

- lib/main.mlx
We accidentally forgot to update the other list of flags, this PR adds the names of the environment variables to enable/disable the behaviors.
> Mention that the other flags can also be enabled for regular builds

- lib/main.mlx
> fix(typo): correct portable-lock-dirs

- .github/workflows/shellcheck.yml
> chore(ci): add shellcheck
