ocaml-dune/binary-distribution

- .github/workflows/binary.yaml
- main.css
- sandworm/bin/dune
- sandworm/bin/main.ml
- sandworm/dune-project
- sandworm/lib/metadata.ml
- sandworm/lib/web.ml
- sandworm/sandworm.opam
I was finally able to complete this PR after some deployment issues. The goal of this PR is to ensure we are more transparent in the way we build our binaries. To achieve this goal, we are now doing two things:
1. We use artifact certificates for each build thanks to GitHub Actions ([documentation here](https://docs.github.com/en/actions/security-for-github-actions/using-artifact-attestations/using-artifact-attestations-to-establish-provenance-for-builds)) :lock: The certificates are uploaded to the server and can be verified using `gh` from GitHub. I didn't add the `SHA256` as the certificate mechanism is stronger than the `SHA256`. Don't hesitate to tell me if you think it is a must to have!
2. It displays the commit when we build `dune`. It is easier for the user to check in the `dune` …
> feat: certify the builds

- README.md
- sandworm/bin/main.ml
- sandworm/lib/metadata.ml
This PR ensures that the _metadata.json_ file is the reflection of the situation on the S3 bucket. It makes sure that every date is related to the last binary information.
Indeed, every time we trigger the build the same day, it would add a new section with the new information and override the binary in the S3 bucket. However, it would add a new section in _index.html_, instead of updating it.  This is __not__ the behavior we want. 
_metadata.json_ must respect the uniqueness invariant: we have only __one__ build for each day, corresponding to the last build we made.
> feat: ensure unicity of each bundle

- .github/workflows/binary.yaml
By using `strip` we could reduce the size of our binaries, thanks to @gridbugs suggestion :+1: 
The flag is for removing all symbols and relocation information:
>  -s --strip-all   Remove all symbol and relocation information
> feat: reduce binary size with strip

- sandworm/bin/main.ml
- sandworm/lib/metadata.ml
- sandworm/lib/web.ml
This PR adds a `/latest/<arch>` URL to the Dune Binary Distribution system. Also, it provides a mechanism to update the binaries every time it is build with the latest version. It makes it easier for users to grab the dune version. 
The website displays a `Latest` section at the top, which are just pointers to the latest built binaries.
This PR must be merged after #4 to make sure we have certificates available for the latest build.
> feat: support latest binary downloading

- dune-nix.patch
The dune "binaries" on macos were actually just the wrapper bash scripts created by nix. This changes the experimental build on macos to take the actual dune binary files.
> Fix experimental build on macos

- dune-nix.patch
The patch needs mail metadata to be applied by the github action.
> Fix patch format

- .github/workflows/binary.yaml
- test/dune-project
Following a discussion with @gridbugs, I propose a simple test to check that the binary are set with the correct flags. It simply tries to lock a package with one dependency (sqlite3 because it's a package with few deps) and run dune build. This is another step to try and verify that our binaries are correct before pushing them.
_N.B_: reopening of #21
> test: check binaries are correct before pushing

- .github/workflows/binary.yaml
There was an issue with `needs` as `binary` was a transitive dep. The result was that it wasn't in the scope anymore. It makes the CI failed because no change (no new commit) was detected.
> fix: use the correct GH path for commits

- dune-locking.patch
The patch was expecting a result because the function was changed on upstream dune. Adding the `_exn` makes the typer happy again.
> fix: sync  with upstream dune

- Dockerfile
- install
- sandworm/bin/config.ml
- sandworm/bin/main.ml
- sandworm/lib/rclone.ml
- sandworm/lib/web.mlx
This PR updates various parts of the project to support new URLS:
- It moves the bucket from download.dune.ci.dev to get.dune.build
- It changes the code to also upload the `install` file to the bucket
I have also changed the configuration in GitHub Actions to push the new binaries to get.dune.build. These changes are related to building the website with OCurrent and deploy to the new URLs to make the preview of Dune officially public. It is related to https://github.com/ocurrent/ocurrent-deployer/issues/235.
> feat: support new dune.build URLs

- .github/workflows/binary.yaml
- install
This PR superseeds #38. It was tested using this [GitHub actions](https://github.com/ocaml-dune/binary-distribution/actions/runs/11139847470/job/30957906388). It adds an update to the install script to build dune from the tarball now. Some changes are kept so the website keep running (still embedding the executable). Future PRs will remove this when the design of the website will be completed :+1:
> feat: build and use tarballs on install

- Dockerfile
Removing the install script from the Dockerfile (as it was moved to the bucket) makes the people using the legacy version to lose the script.
> fix: legacy install support

- install
See https://news.ycombinator.com/item?id=40201920 for details. Essentially: try not to execute code before we have made sure we got all of it downloaded.
> Add a guard against accidental partial script execution

- sandworm/lib/web.mlx
This adds more options to `curl` to fail in a more sensible way if there are issues. Especially the `-L` option would've been useful as we have set up a redirect.
Convienient explanation of the options in question by [explainshell curl -fsSL](https://explainshell.com/explain?cmd=curl+-fsSL)
> More secure curl options

- install
Deleting the tmp dir with a command in the script leaves the potential for the script to exit before reaching that line, leaving the tmp dir undeleted. Further, deleting the tmp dir with "rmdir" will only work if the tmp dir is empty which may be the case if the script failed to move some of the files during installation. This change addresses both these issues.
> Ensure tmp dir is deleted on exit

- static/install
The dim text was hard to read on dark themed terminals. I've tested this change on light and dark terminals and the result is more readable.
> Readable colours on dark terminals

- .github/workflows/binary.yaml
This PR fixes an issue in the PR that moves to `dream`. As it does not generate an `index.html` the CI wasn't working anymore.
> fix: don't try to push index.html

- shell.nix
The shell.nix file contains all system packages needed to build/run the opam packages which this project depends on.
> Add minimal shell.nix

- lib/web.mlx
"so far" implies "all the releases" but actually that's not what the list is doing, it just lists the latest 30.
> Improve the wording

- bin/main.ml
The reason why we weren't able to access the script was just because it was pushed to the wrong directory. I have missed this while changing the structure to use Dream.
> fix: push the script to the root location

- bin/server.ml
This PR changes the behaviour of the `/latest` endpoint. Instead of just providing an URL, it redirects to the correct destination.
> feat: use latest to redirect to correct URL

- .github/workflows/binary.yaml
This is an attempt at fixing #45.
In the issue @Leonidas-from-XIV raises a good point: if the previous run wasn't 24h ago for some reason, then this will make it wait until a new commit. This isn't ideal, but there is no direct way in github actions to get the status of the previous run. A solution may be to hit the github api and ask there, but that requires a token which we may or may not have.
Another would be to ask around the system where we put the previous binaries, and compute the time difference...
Just wanted to get the ball rolling
> Avoid unnecessary builds if no changes happened since last run

- lib/web.mlx
Thought it might be nice to link to the relevant documents directly.
> Add links to the package management documentation

- .github/workflows/binary.yaml
This PR fixes #45 as it was not fully compliant with the GitHub Actions YAML syntax. It moves the check to a prior step instead of directly doing it in the build stage itself. I tested the actions before, and it seems to work. We will be fully confident when it will be triggered for the first time :+1:
> fix: check_build action

- .github/workflows/binary.yaml
This PR temporary disable the duplication check. It can be set back again when the script does not rely on the date of the day any more.
Temporary workaround for #98.
> fix: temporary deactivate the duplication check

- lib/metadata.ml
This makes the automatic commit diffs a bit more readable.
Closes #94.
> Enable prettyprinting of the generated JSON

- .github/workflows/binary.yaml
Since #105 have been merged, we can reintroduce this feature as we don't depend on the date any more :+1:
> chore(ci): reactivate build on change feature

- static/install
If we check for `tar` we might as well check that tar can uncompress via `g(un)zip` and then we might as well test for `curl` if the user used `wget` or their browser to download (or like me, a docker image).
> Add checks for more commands that we use

- .github/workflows/binary.yaml
- README.md
This PR fixes #51. To test a branch, we can now push force on staging and, trigger the pipeline. It will push the binary to a "<url>/test/..." location. It will use sed to modify the config to point to the right bucket (the test one). This way, we can test our scripts in real-time. I agree this is not the cleanest way to have a test environment, but it is the easiest one.
> chore: staging use a subdir for test

- .github/workflows/binary.yaml
I'll add that stage back once the build finishes, but I need this check to be disabled to rebuild the archive to include the env and completions dirs. Heads up @maiste.
> Temporarily remove check_build to allow archive to be rebuilt

- static/install
This fixes an issue where installing dune multiple times results in multiple additions to the shell rc file. The most naive way to achive this would just be to not modify the shell rc if it looks like dune has already been installed. The problem with that approach is that we may want to update the env changes in the future. Moving all env changes to a separate file sourcef from the shell rc gives us the ability to change the contents of that file in future updates without needing to modify the shell rc.
It also simplifies the install script as we no longer need to put shell commands in bash strings and deal with the complexities of escaping characters correctly.
> Run env scripts from external files

- .github/workflows/binary.yaml
This PR ensures we are rebuilding when using the dispatch functionality of GitHub Actions. Indeed, if someone is explicitly asking to rebuild the binaries, it is consciously. We must not block the building. The smart building should only occur when using the scheduling pipeline.
> feat: build on workflow dispatch event

- static/install
On my system this leads to `/tmp/dune-install.RANDOM` which is a bit nicer (given it is a `tmpfs`) than just writing a temporary thing into the users home directory.
Of course the downside is that `mv` is not atomic and we might run out of space but these cases seem fairly rare.
> Create temporary directory in temporary location

- completions/bash.sh
The new script was generated according to the instructions in https://github.com/gridbugs/dune-completion-scripts and adds the completion for the new command `dune tools exec ocamlformat`.
> Update completion script

- .github/workflows/binary.yaml
- tool-wrappers/ocamllsp
This script runs the ocamllsp dev tool in an environment where the ocamlformat dev tool is in PATH, first making sure that the ocamlformat and ocamllsp dev tools are installed. If the script is run anywhere other than a dune project with a lockdir then it falls back to running `ocamllsp` from PATH.
This change doesn't install the `ocamllsp` script yet, it just adds it to the archive. Installing the script will come in a later change to make sure we don't update the install script before at least one archive contains the wrapper script.
> Add ocamllsp wrapper script

- static/install
This change downloads the snapshot of a git repo containing revisions of opam-repository and dune-overlays I've previously uploaded to [opam-repository-snapshots](https://github.com/ocaml-dune/opam-repository-snapshots/releases/tag/opam-repository-924ed6223cc22c606b7d5e7bb9793eaa1519e708).
It comes in two variants:
1. ZSTD compressed. It saves about 23MB and uncompresses fast, but `zstd` isn't very common of a tool to have installed, but for those that do this can make a decent positive difference.
2. Uncompressed. It's the same file as the tarball that the `zst` decompresses to. I decided against using gzip as fallback as that takes 4x as long to decompress as `zstd` and only yielded 11 MB savings even if using Zoepfli. This is unsurpsising given that git uses some compression …
> Download and unpack opam-repo revision store cache

- static/install
Wildcards are not expanded inside quoted strings.
> Fix installation of tool wrappers

- static/install
By default files unpacked by tar are owned by the current user. But when running as root (e.g. Docker) then tar will unpack with the owner set to the owner from the tar archive instead of the user (as tar stores the UID in the metadata). This potentially leads to files with strange owners and among others, git refusing to touch the cached repository.
To take an example provided by @mefyl:
```
FROM alpine
RUN apk add bash curl git make npm gcc g++ tzdata
RUN curl -fsSL https://get.dune.build/install | sh
ENV PATH="/root/.dune/bin:$PATH"
WORKDIR /root
RUN git clone https://github.com/mefyl/timmy
RUN git config --global --add safe.directory /root/.cache/dune/git-repo
WORKDIR /root/timmy
RUN dune pkg lock
RUN dune build
```
Line 7 is necessary as the line 3 executes the script as root, thus …
> Extract archives as the current user instead of the archive user

- lib/web.mlx
Previously it was surrounded by "code" tags which caused it to appear on a separate line from the surrounding text which doesn't appear to be the intended formatting. This changes it to use "span" tags which cause it to appear inline with the surrounding text.
> Fix formatting of gh program name

- lib/web.mlx
Without the protocol, it jumps to `https://preview.dune.build/github.com/ocaml-dune/binary-distribution`...
> Fix GitHub link

- lib/web.mlx
@ElectreAAS merged a PR that enables the toolchain support by default thus we can simplify the options that are required now.
> No need to enable toolchains anymore on recent builds

- lib/web.mlx
Now that a compatible version of the plugin has been released we can specify the minimum supported version in the instructions.
> Add version number of vscode plugin

- lib/web.mlx
Mlx seems to emit all html on a single line, include inside `<pre>` tags. Thus the apparent line breaks in code blocks cannot be copy/pasted, and copy/pasting results in all the code on a single line. This change adds explicit html line breaks at the end of each line of code to work around this issue.
> Add line breaks to code blocks

- dune-project
Prior to this change one gets the following error when locking the project:
```
remote: Not Found
fatal: repository 'https://github.com/tmattio/opam-tailwindcss/archive/e5bb6361a50c7cc5cad802311e609336583ca08f.tar.gz/' not found
File "dune-project", line 59, characters 2-107:
59 |   "git+https://github.com/tmattio/opam-tailwindcss/archive/e5bb6361a50c7cc5cad802311e609336583ca08f.tar.gz")
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: Failed to run external command:
'git ls-remote "https://github.com/tmattio/opam-tailwindcss/archive/e5bb6361a50c7cc5cad802311e609336583ca08f.tar.gz"'
Hint: Check that this Git URL in the project configuration is correct:
"https://github.com/tmattio/opam-tailwindcss/archive/e5bb6361a50c7cc5cad802 …
```
> Fix tailwindcss url

- static/install
Inspired by @smorimoto's #126 I think these options make sense to add in the script:
* `--tlsv1.2` will require TLS 1.2+ (but also allow 1.3) thus prevents it from using older, less secure TLS versions
* `--proto '=https'` will prevent redirecting to HTTP. Since we download from GitHub and where GitHub redirects to is outside of our control I think there is a point in making sure it will fail if it redirects to a HTTP location.
Both our server and Github support TLSv1.2, the question is more whether our users have `curl` that support these options. My `curl` has them and the one in Alpine as well, so maybe this is fine without a feature check?
WDYT?
> Use more restrictive options to make `curl` safer

- .github/workflows/binary.yaml
In the past, we have been uploading executable to https://get.dune.build. When we moved to a TAR version of the scripts, I kept the executable uploaded to make sure people with the old script would get the correct version.
Now we don't serve the old script any more and there is no more link to the executables (as we only display the 30 months version), we can confidently remove the copy of the script to the static server.
Fixes #47
> fix: stop uploading executables

- lib/web.mlx
As suggested in #106, it can be confusing for the user to create a new project. The proposed solution makes it clearer what happens when using `dune init` when you create a project (the name and how to invoke it).
This is more for people who are not used to `dune`, but I would expect advanced `dune` users to skip this part when downloading the Dune Developer Preview.
> feat: make the getting started clearer

- env/env.bash
- env/env.fish
- env/env.zsh
- lib/web.mlx
- static/install
This changes the location into which Dune is installed into the users `.local` folder, which is fairly standard for a lot of user-installed packages.
It also changes the locations for env & completions to fit with the conventions and reworks the config editing to compute the paths. I got them all wrong all the time, missing one or the other component so now the computer does all the computing for me.
Finally it adds a fallback for when SHELL isn't set. Dash doesn't set SHELL so it prints an error (and continues with the `*` branch anyway). This makes avoids the error message while still executing the same fallback branch.
There's two reasons for this change:
* `.local` is a fairly standard convention and people might actually have `~/.local/bin` in their paths
* `.dune` conflicts with …
> Install to `.local` instead of `.dune`

- lib/container.mlx
Use the default `/js/script.js` rather than the `/js/file-downloads.js`.
Downloads are now tracked by parsing the Caddy log files and pushing those events to Plausible.  Leaving this unchanged will double-count some downloads.
> Use page view script

- completions/bash.sh
This PR adds a guard against `compopt` as it can be not available in old bash version and in zsh (see [issue](https://github.com/crystal-lang/crystal/issues/12232)).
> fix: ensure compopt available

- dune-project
- dune.lock/lock.dune
- dune.lock/logs.pkg
- dune.lock/lwt.pkg
- dune.lock/lwt_ppx.pkg
- dune.lock/tailwindcss.pkg
- dune.lock/topkg.pkg
- dune.lock/uutf.pkg
Now Dune Package Management is able to use tar URL, it is a good idea to go
back to the tailwind tar.gz URL to make sure we don't download an history of
executables.
Fixes #135
> chore(tailwindcss): move to targz lighter URL

- lib/main.mlx
This PR introduces the new binary dev tools flag to the website.
> web: add the new binary flag

- lib/main.mlx
The flag section was using the old syntax.
> fix: use the correct flag names

- lib/main.mlx
Outdated documentation pointed out by @shym.
> Mention portable lock dirs

- lib/main.mlx
Disabled in https://github.com/ocaml/dune/pull/11882
> Don't mention binary dev tools anymore, they're not enabled anymore

- tool-wrappers/ocamllsp
A recent update to macOS appears to have changed the paste command so that it no longer assumes its inputs is stdin when no input file is specified. It does still follow the convention of interpreting an input file named "-" as stdin, so the fix is to pass "-" as the input file to paste.
> Fix issue with paste on macOS
